### ISSUE TITLE
🤖 Dependabot Container Image Monitoring

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/staff-device-dns-server#161]
Issue created against dependabot-core - [https://github.com/dependabot/dependabot-core/issues/3929](url)

Update dependabot to monitor Alpine [versions](https://github.com/ministryofjustice/staff-device-dns-server/blob/main/dns-service/Dockerfile). 

```
FROM ruby:3.2.1-alpine3.16
...
```

**Comment by Gary-H9** [comment]
Testing done in [this](https://github.com/Gary-H9/playground) repository.

**Comment by ASTRobinson** [comment]
issue raised with Dependabot https://github.com/dependabot/dependabot-core/issues/7320

**Comment by juddin927** [comment]
Dependabot doesnt support this at this point in time,going to move this to review and add this to a know issue.
